# -*- coding: utf-8 -*-
"""RNN_AS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Fckkb9sVM_AJLfdiB8xLHhzAwm6IH-j
"""

import numpy as np
import pandas as pd
import os
from pathlib import Path

# Reduce logs informativos de TensorFlow (debe ir antes del import de tf)
os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")

# Workaround para RTX 5060 Ti (compute capability 12.0): desactivar JIT compilation
# que causa problemas en primera ejecución. TensorFlow usará kernels precompilados o CPU
os.environ["TF_FORCE_GPU_ALLOW_GROWTH"] = "true"
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

import tensorflow as tf

# Configurar TensorFlow para usar CPU durante construcción del modelo para evitar
# errores de CUDA_ERROR_INVALID_HANDLE en la compilación JIT de primera ejecución
tf.config.set_visible_devices([], 'GPU')
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# ==========================================
# 1. Cargar datasets desde CSV
# ==========================================
print("Cargando datasets...")

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
TRAIN_CSV = DATA_DIR / "sentiment.csv"
TEST_CSV = DATA_DIR / "Equal.csv"

print(f"Ruta de datos resuelta: {DATA_DIR}")

for csv_path in (TRAIN_CSV, TEST_CSV):
    if not csv_path.exists():
        raise FileNotFoundError(f"No se encontro el archivo: {csv_path}")

train_df = pd.read_csv(TRAIN_CSV, encoding='latin-1')
test_df = pd.read_csv(TEST_CSV, encoding='latin-1')

print(f"TensorFlow version: {tf.__version__}")
gpus = tf.config.list_physical_devices('GPU')
print(f"GPUs detectadas por TensorFlow: {gpus if gpus else 'ninguna'}")

# Limpiar datos: eliminar filas con valores faltantes en Review y Sentiment
train_df = train_df.dropna(subset=['Review', 'Sentiment'])
test_df = test_df.dropna(subset=['Review', 'Sentiment'])

# Convertir sentimientos a binario: positive=1, negative=0
train_df['Sentiment'] = train_df['Sentiment'].map({'positive': 1, 'negative': 0})
test_df['Sentiment'] = test_df['Sentiment'].map({'positive': 1, 'negative': 0})

# Eliminar filas con valores NaN después del mapeo
train_df = train_df.dropna()
test_df = test_df.dropna()

frases = train_df['Review'].values.tolist()
etiquetas = train_df['Sentiment'].values.astype(int).tolist()

test_frases = test_df['Review'].values.tolist()
test_etiquetas = test_df['Sentiment'].values.astype(int).tolist()

print(f"✓ Dataset de entrenamiento: {len(frases)} reviews")
print(f"✓ Dataset de test: {len(test_frases)} reviews")
print(f"  Positivos (train): {sum(etiquetas)}")
print(f"  Negativos (train): {len(etiquetas) - sum(etiquetas)}")
print(f"  Positivos (test): {sum(test_etiquetas)}")
print(f"  Negativos (test): {len(test_etiquetas) - sum(test_etiquetas)}")

# ==========================================
# 2. Tokenización
# ==========================================
print("\nTokenizando datos...")
tokenizer = Tokenizer(num_words=5000, oov_token="<OOV>")
tokenizer.fit_on_texts(frases)

secuencias = tokenizer.texts_to_sequences(frases)
test_secuencias = tokenizer.texts_to_sequences(test_frases)

# Longitud máxima de secuencia
max_len = max(len(seq) for seq in secuencias + test_secuencias)

# Rellenar secuencias
X = pad_sequences(secuencias, maxlen=max_len, padding="post")
y = np.array(etiquetas)

X_test = pad_sequences(test_secuencias, maxlen=max_len, padding="post")
y_test = np.array(test_etiquetas)

# Dividir dataset de entrenamiento en train/validación (80/20)
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("=== Ejemplos de tokenización ===")
for i in range(3):
    print(f"Frase: {frases[i][:80]}...")
    print(f"Secuencia: {secuencias[i][:10]}...")
    print("---")

print(f"\nForma de X_train: {X_train.shape}")
print(f"Forma de y_train: {y_train.shape}")
print(f"Forma de X_val: {X_val.shape}")
print(f"Forma de y_val: {y_val.shape}")
print(f"Forma de X_test: {X_test.shape}")
print(f"Forma de y_test: {y_test.shape}")
print(f"Longitud máxima de secuencia: {max_len}")

# ==========================================
# 3. Definir modelo RNN mejorado
# ==========================================
from tensorflow.keras.layers import Dropout
from tensorflow.keras.regularizers import l2
from tensorflow.keras.optimizers import Adam

vocab_size = len(tokenizer.word_index) + 1

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=16, input_shape=(max_len,)),
    Dropout(0.3),  # Regularización: desactivar 30% de neuronas aleatoriamente
    SimpleRNN(32, activation="tanh", return_sequences=True, kernel_regularizer=l2(0.001)),
    Dropout(0.3),
    SimpleRNN(16, activation="tanh", kernel_regularizer=l2(0.001)),
    Dropout(0.3),
    Dense(8, activation="relu", kernel_regularizer=l2(0.001)),
    Dropout(0.2),
    Dense(1, activation="sigmoid")
])

# Compilar con Learning Rate controlado
optimizer = Adam(learning_rate=0.001)  # Learning rate más bajo que el default (0.001)
model.compile(
    optimizer=optimizer,
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

print("\n=== Resumen del modelo ===")
model.summary()

# Re-habilitar GPU para entrenamiento (kernels ya estarán compilados)
gpus = tf.config.list_physical_devices('GPU')
if gpus:
    try:
        for gpu in gpus:
            tf.config.experimental.set_memory_growth(gpu, True)
    except RuntimeError as e:
        # Esto es esperado si la GPU ya fue inicializada
        pass

# ==========================================
# 4. Entrenamiento con Early Stopping
# ==========================================
from tensorflow.keras.callbacks import EarlyStopping

# Early Stopping: detiene el entrenamiento si la validación no mejora en 3 épocas
early_stopping = EarlyStopping(
    monitor='val_loss',           # Monitorear validación loss
    patience=3,                   # Esperar 3 épocas sin mejora
    restore_best_weights=True,    # Restaurar pesos de la mejor época
    verbose=1
)

history = model.fit(
    X_train,
    y_train,
    validation_data=(X_val, y_val),  # Validar en cada época
    epochs=30,
    batch_size=32,  # Aumentado de 4 a 32 para reducir ruido en gradientes
    callbacks=[early_stopping],
    verbose=1
)

# ==========================================
# 5. Evaluación en entrenamiento y test
# ==========================================
print("\n=== Evaluación ===")
loss_train, acc_train = model.evaluate(X_train, y_train, verbose=0)
print(f"\n📊 ENTRENAMIENTO:")
print(f"  Pérdida: {loss_train:.4f}")
print(f"  Exactitud: {acc_train:.4f}")

loss_val, acc_val = model.evaluate(X_val, y_val, verbose=0)
print(f"\n📊 VALIDACIÓN:")
print(f"  Pérdida: {loss_val:.4f}")
print(f"  Exactitud: {acc_val:.4f}")

loss_test, acc_test = model.evaluate(X_test, y_test, verbose=0)
print(f"\n📊 TEST (RATIO.csv):")
print(f"  Pérdida: {loss_test:.4f}")
print(f"  Exactitud: {acc_test:.4f}")

# Predicciones detalladas
y_pred_proba = model.predict(X_test, verbose=0)
y_pred = (y_pred_proba >= 0.5).astype(int).flatten()

print(f"\n📈 MÉTRICAS DETALLADAS (Test Set):")
print(classification_report(y_test, y_pred, target_names=['Negativo', 'Positivo']))

print("Matriz de confusión:")
print(confusion_matrix(y_test, y_pred))

# ==========================================
# 6. Predicción con frases nuevas (ejemplos)
# ==========================================
print("\n=== Predicciones con frases nuevas ===")
nuevas_frases = [
    "excelente producto muy recomendado",
    "terrible calidad no lo compren",
    "muy buena compra estoy satisfecho",
    "pésimo servicio muy decepcionado",
    "increíble precio y calidad"
]

X_nuevas = tokenizer.texts_to_sequences(nuevas_frases)
X_nuevas = pad_sequences(X_nuevas, maxlen=max_len, padding="post")

predicciones = model.predict(X_nuevas, verbose=0)

for frase, pred in zip(nuevas_frases, predicciones):
    prob = float(pred[0])
    etiqueta = "positivo" if prob >= 0.5 else "negativo"
    print(f"Frase: '{frase}'")
    print(f"Probabilidad positiva: {prob:.4f}")
    print(f"Predicción: {etiqueta}")
    print("---")

# ==========================================
# 7. Función para predecir una sola frase
# ==========================================
def predecir_sentimiento(frase):
    """Predice el sentimiento de una frase nueva"""
    secuencia = tokenizer.texts_to_sequences([frase])
    secuencia = pad_sequences(secuencia, maxlen=max_len, padding="post")
    pred = model.predict(secuencia, verbose=0)[0][0]
    etiqueta = "POSITIVO ✓" if pred >= 0.5 else "NEGATIVO ✗"

    print(f"\n{'='*50}")
    print(f"Frase: {frase}")
    print(f"Probabilidad positiva: {pred:.4f}")
    print(f"Predicción: {etiqueta}")
    print(f"{'='*50}")

# Ejemplos de uso
print("\n=== Predicciones de ejemplo con nuevas frases ===")
predecir_sentimiento("la atención fue excelente y el producto llegó rápido")
predecir_sentimiento("el producto salió muy malo y defectuoso")
predecir_sentimiento("muy buena compra recomendado al 100%")
