# -*- coding: utf-8 -*-
"""RNN_AS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-Fckkb9sVM_AJLfdiB8xLHhzAwm6IH-j
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

# ==========================================
# 1. Cargar datasets desde CSV
# ==========================================
print("Cargando datasets...")
train_df = pd.read_csv('./data/sentiment.csv', encoding='latin-1')
test_df = pd.read_csv('./data/RATIO.csv', encoding='latin-1')

# Limpiar datos: eliminar filas con valores faltantes en Review y Sentiment
train_df = train_df.dropna(subset=['Review', 'Sentiment'])
test_df = test_df.dropna(subset=['Review', 'Sentiment'])

# Convertir sentimientos a binario: positive=1, negative=0
train_df['Sentiment'] = train_df['Sentiment'].map({'positive': 1, 'negative': 0})
test_df['Sentiment'] = test_df['Sentiment'].map({'positive': 1, 'negative': 0})

# Eliminar filas con valores NaN después del mapeo
train_df = train_df.dropna()
test_df = test_df.dropna()

frases = train_df['Review'].values.tolist()
etiquetas = train_df['Sentiment'].values.astype(int).tolist()

test_frases = test_df['Review'].values.tolist()
test_etiquetas = test_df['Sentiment'].values.astype(int).tolist()

print(f"✓ Dataset de entrenamiento: {len(frases)} reviews")
print(f"✓ Dataset de test: {len(test_frases)} reviews")
print(f"  Positivos (train): {sum(etiquetas)}")
print(f"  Negativos (train): {len(etiquetas) - sum(etiquetas)}")
print(f"  Positivos (test): {sum(test_etiquetas)}")
print(f"  Negativos (test): {len(test_etiquetas) - sum(test_etiquetas)}")

# ==========================================
# 2. Tokenización
# ==========================================
print("\nTokenizando datos...")
tokenizer = Tokenizer(num_words=5000, oov_token="<OOV>")
tokenizer.fit_on_texts(frases)

secuencias = tokenizer.texts_to_sequences(frases)
test_secuencias = tokenizer.texts_to_sequences(test_frases)

# Longitud máxima de secuencia
max_len = max(len(seq) for seq in secuencias + test_secuencias)

# Rellenar secuencias
X = pad_sequences(secuencias, maxlen=max_len, padding="post")
y = np.array(etiquetas)

X_test = pad_sequences(test_secuencias, maxlen=max_len, padding="post")
y_test = np.array(test_etiquetas)

print("=== Ejemplos de tokenización ===")
for i in range(3):
    print(f"Frase: {frases[i][:80]}...")
    print(f"Secuencia: {secuencias[i][:10]}...")
    print("---")

print(f"\nForma de X (train): {X.shape}")
print(f"Forma de y (train): {y.shape}")
print(f"Forma de X_test: {X_test.shape}")
print(f"Forma de y_test: {y_test.shape}")
print(f"Longitud máxima de secuencia: {max_len}")

# ==========================================
# 3. Definir modelo RNN
# ==========================================
vocab_size = len(tokenizer.word_index) + 1

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=16, input_shape=(max_len,)),
    SimpleRNN(32, activation="tanh"),
    Dense(1, activation="sigmoid")
])

model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

print("\n=== Resumen del modelo ===")
model.summary()

# ==========================================
# 4. Entrenamiento
# ==========================================
history = model.fit(
    X,
    y,
    epochs=30,
    batch_size=4,
    verbose=1
)

# ==========================================
# 5. Evaluación en entrenamiento y test
# ==========================================
print("\n=== Evaluación ===")
loss_train, acc_train = model.evaluate(X, y, verbose=0)
print(f"\n📊 ENTRENAMIENTO:")
print(f"  Pérdida: {loss_train:.4f}")
print(f"  Exactitud: {acc_train:.4f}")

loss_test, acc_test = model.evaluate(X_test, y_test, verbose=0)
print(f"\n📊 TEST (RATIO.csv):")
print(f"  Pérdida: {loss_test:.4f}")
print(f"  Exactitud: {acc_test:.4f}")

# Predicciones detalladas
y_pred_proba = model.predict(X_test, verbose=0)
y_pred = (y_pred_proba >= 0.5).astype(int).flatten()

print(f"\n📈 MÉTRICAS DETALLADAS (Test Set):")
print(classification_report(y_test, y_pred, target_names=['Negativo', 'Positivo']))

print("Matriz de confusión:")
print(confusion_matrix(y_test, y_pred))

# ==========================================
# 6. Predicción con frases nuevas (ejemplos)
# ==========================================
print("\n=== Predicciones con frases nuevas ===")
nuevas_frases = [
    "excelente producto muy recomendado",
    "terrible calidad no lo compren",
    "muy buena compra estoy satisfecho",
    "pésimo servicio muy decepcionado",
    "increíble precio y calidad"
]

X_nuevas = tokenizer.texts_to_sequences(nuevas_frases)
X_nuevas = pad_sequences(X_nuevas, maxlen=max_len, padding="post")

predicciones = model.predict(X_nuevas, verbose=0)

for frase, pred in zip(nuevas_frases, predicciones):
    prob = float(pred[0])
    etiqueta = "positivo" if prob >= 0.5 else "negativo"
    print(f"Frase: '{frase}'")
    print(f"Probabilidad positiva: {prob:.4f}")
    print(f"Predicción: {etiqueta}")
    print("---")

# ==========================================
# 7. Función para predecir una sola frase
# ==========================================
def predecir_sentimiento(frase):
    """Predice el sentimiento de una frase nueva"""
    secuencia = tokenizer.texts_to_sequences([frase])
    secuencia = pad_sequences(secuencia, maxlen=max_len, padding="post")
    pred = model.predict(secuencia, verbose=0)[0][0]
    etiqueta = "POSITIVO ✓" if pred >= 0.5 else "NEGATIVO ✗"

    print(f"\n{'='*50}")
    print(f"Frase: {frase}")
    print(f"Probabilidad positiva: {pred:.4f}")
    print(f"Predicción: {etiqueta}")
    print(f"{'='*50}")

# Ejemplos de uso
print("\n=== Predicciones de ejemplo con nuevas frases ===")
predecir_sentimiento("la atención fue excelente y el producto llegó rápido")
predecir_sentimiento("el producto salió muy malo y defectuoso")
predecir_sentimiento("muy buena compra recomendado al 100%")
