# -*- coding: utf-8 -*-
"""RNN_generacion_flores.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YyF9G_vvYYnXtzWaTAq-sd5bzUjhPe6-

# Práctica: Generación de texto con RNN (nombres de flores)

Objetivo: entrenar una RNN a nivel carácter para generar nuevos nombres de flores.

## 1. Librerías
"""

import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from tensorflow.keras.preprocessing.sequence import pad_sequences

"""## 2. Dataset (nombres de flores)

"""

flores = [
    "rosa", "tulipan", "girasol", "margarita", "orquidea",
    "jazmin", "clavel", "azucena", "lirio", "violeta",
    "dalia", "gardenia", "petunia", "hibisco", "lavanda",
    "bugambilia", "camelina", "anemona", "begonia", "calendula",
    "hortensia", "zinnia", "amarilis", "amapola", "jacintos",
    "magnolia", "camelia", "azalea", "crisantemo", "diente de leon",
    "flor de cerezo", "fresa", "pasionaria", "corona de cristo", "aleli",
    "mandevila", "geranio", "achimenes", "flamenca", "trebol"
]
texto = " ".join(flores)
print(texto)

"""## 3. Vocabulario de caracteres

"""

chars = sorted(list(set(texto)))
char2idx = {c:i for i,c in enumerate(chars)}
idx2char = {i:c for c,i in char2idx.items()}
vocab_size = len(chars)
print(chars)
print("Vocab size:", vocab_size)

"""## 4. Codificación

"""

texto_codificado = [char2idx[c] for c in texto]

"""## 5. Crear secuencias

"""

seq_length = 5
X = []
y = []
for i in range(len(texto_codificado)-seq_length):
    X.append(texto_codificado[i:i+seq_length])
    y.append(texto_codificado[i+seq_length])
X = np.array(X)
y = np.array(y)
print(X.shape, y.shape)

"""## 6. Modelo RNN

"""

model = Sequential([
    Embedding(input_dim=vocab_size, output_dim=16, input_length=seq_length),
    SimpleRNN(32, activation='tanh'),
    Dense(vocab_size, activation='softmax')
])
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.summary()

"""## 7. Entrenamiento

"""

model.fit(X, y, epochs=300)

"""## 8. Generación de texto

"""

def generar_texto(model, semilla, longitud=10):
    resultado = semilla
    entrada = [char2idx[c] for c in semilla]
    for _ in range(longitud):
        entrada_pad = pad_sequences([entrada], maxlen=seq_length, truncating='pre')
        pred = model.predict(entrada_pad, verbose=0)[0]
        idx = np.argmax(pred)
        char = idx2char[idx]
        resultado += char
        entrada.append(idx)
    return resultado

"""## 9. Pruebas

"""

semillas = ["ro", "ma", "ca", "la", "die", "tr"]
for s in semillas:
    print(s, "->", generar_texto(model, s, 15))